Clivia Backend😪😪😯/app/home/routes.py
from app import app, db
from flask import ( render_template, request, redirect, url_for, session,
	flash,Blueprint, abort
	)

from flask_login import current_user, login_required

from app.models import User, Categories, Products,Kart
from app.admin.forms import Variations
import random
home = Blueprint('home', __name__)


@home.route('/admin/dashboard/')
@login_required
def admin_dashboard():
	#preventing non admins from accessing the page
	if not current_user.is_admin:
		abort(403)
	return render_template('admin/admin_dashboard.html' , title = "Dashboard")

@home.route('/')
def landing():
	ids = []
	c = Products.query.all()
	for s in c:
		ids.append(s.id)
	sorter = []
	for i in range(3):
		random.randint(1,1000)
		if i in ids:
			sorter.append(i)
	products = Products.query.all()
	return render_template('head.html', products = products, sorter = sorter)

@home.route('/home/')
def homepage():		
	categories = Categories.query.all()
	products = Products.query.all()

	if current_user.is_anonymous:
		count = 0
	else:
		count = Kart.query.filter_by(user_id =current_user.id).count()
	return render_template("home/index.html", title = 'Website name',
	categories = categories, products = products, count=count)

@home.route('/<string:category_name>/')
def shop_by_category(category_name):
	if current_user.is_anonymous:

		count = 0
	else:
		count = Kart.query.filter_by(user_id =current_user.id).count()

	page = request.args.get('page',1, type=int)

	category = Categories.query.filter_by(category_name=category_name).first_or_404()

	product = Products.query.filter_by(categories_id=category.id)\
		.order_by(Products.product_name).paginate(page=page, per_page=6)
	
	for_pagi = Categories.query.filter_by(category_name = Categories.category_name).first_or_404()
	return render_template("home/shop_by_category.html", category = category,\
		product = product, title = "Category: "+ category.category_name,count=count,\
		for_pagi = for_pagi)


@home.route('/productdetails/<string:product_name>/', methods = ["GET","POST"])
def product_details(product_name):
	if current_user.is_anonymous:
		count = 0
	else:
		count = Kart.query.filter_by(user_id =current_user.id).count()
		user =current_user.id
	form = Variations()

	product_detail = Products.query.filter_by(product_name=product_name).first_or_404()
		
	# add to cart
	if form.validate_on_submit():
		# annonymous users
		if current_user.is_anonymous:
			flash('please login before you can add items to your shopping cart','warning')
			return redirect(url_for("home.product_details",\
				product_name = product_detail.product_name))
		# authenticated users
		product_detail.product_size = form.sizes.data
		cart = Kart(user_id=user, product_id=product_detail.id, quantity=1,
		subtotal = product_detail.product_price)
		db.session.add(cart)
		db.session.commit()

		flash("{} has been added to cart".format(product_detail.product_name))	
		return redirect(url_for('home.product_details',\
			product_name = product_detail.product_name ))
	return render_template("home/productdetails.html",
		product_detail = product_detail,title = product_detail.product_name,
		form =form,count=count)

Clivia Backend😪😪😯/app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock title%}
{% block body %}

<body>

	<div class="container-fluid">
	{% if categories %}

	<div class="row d-block">
		{% for category in categories %}
	<a href="{{ url_for('home.shop_by_category', category_name=category.category_name) }}">
		<div class="col l4 s12 m6" >
			<div class="card-panel hoverable" style="max-height:270px; background-color:#FFFFFF;">
					<div class="card-image" style="margin-left:auto;margin-right: auto;">
							<img class="responsive-img" src="{{category.category_image}}"  >
							<div class="caption">
							<span class="card-title" style="margin-bottom:7px;">
								<strong style="font-size:16px;font-family: 'Roboto', sans-serif;color: #000;">
									{{ category.category_name }}
								</strong>
							</span>
							</div>
					
						</div>
				</div>
		</div>
	</a>
		{% endfor %}
	</div>



	{% endif %}
	</div>
</body>

{% endblock %}

Clivia Backend😪😪😯/app/templates/home/productdetails.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title%}
{% block body %}
{% if product_detail %}

<div class="container-fluid clearfix" style="max-width:90%; margin-left: auto; margin-right: auto;">
    <div class="float-left" style=" width:50%;">
                <img  class="responsive-img" src="{{ product_detail.product_image }}">

    </div>
    <div class="float-right" style="width:48%;">
        <div>
                <span class="product-name">
                        {{ product_detail.product_name }}
                </span>
                <h5 style="font-size:19px">
                    Stock: <span style="color:forestgreen;">{{ product_detail.product_stock }}</span>
                </h5>
                <article>
                        <h5 style="font-size: 19px;">
                                Description of {{ product_detail.product_name }}
                         </h6>
                        <p style="font-size:15px;">
                        <div class="product-description">
                            {{product_detail.product_description }}
                        </div>
                        </p>
                </article>
                <section>
                    <section>
                        <form class="form-inline" method="POST">
                            {{ form.hidden_tag() }}
                            

                        {% for subfield in form.sizes %}
                        <div class="radio">
                            <style>
                                label
                                {
                                    margin-right: 5px;
                                   font-size: 14px;
                                    color:inherit;

                                }
                            </style>
                                  {{ subfield }} 
                                  {{ subfield.label }}  
                        </div>
                              
                        {% endfor %}
                    <div>
                            {{ form.submit(class="btn btn-primary d-block")}}   
                            <!-- change button and render form from forms.py -->
                           
                        </div>
                  </section>
                    
                    </form>




                </section>
        </div>
              

        
    </div>
        
</div>

{% endif %}
{% endblock %}

Clivia Backend😪😪😯/app/templates/home/shop_by_category.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title%}
{% block body %}

{% if category %}
<style>
    .title
    {
        margin: 0;
        padding: 0;
        margin-left: 20px;
        margin-top: 6px;

    }
    .product-name
    {
        
        font-family: Roboto,Helvetica,Arial,sans-serif;
        font-weight: 500;
        font-size: 14px;
        line-height: 17px;
        color: #000;
        margin: 3px 0 5px 0;
        text-align: left;
        white-space: normal;
        overflow: hidden;
    }
    .price{
        
        margin-left: 20px;
        font-family: Roboto,Helvetica,Arial,sans-serif;
        font-weight: 400;
        font-size: 13px;
        line-height: 17px;
        color: #202020;
        display: inline-block;
    }
</style>

{% if category.product %}
<div class="row d-block">
        {% for product_list in product.items %}
	<a href="{{ url_for('home.product_details', product_name = product_list.product_name ) }}">
        <div class="col l4 s12 m6">
			<div class="card-panel hoverable" style="max-height:360px; background-color:#FFFFFF;">    
                <div class="card-image" style="margin-left:auto;margin-right: auto;">
                        <div class="thumbnail" style="height:220px;margin-bottom: 0px;">
                            <img class="responsive-img" src="{{ product_list.product_image }}" style="height:100%;">
                        </div>
                        <h6 class="title">
                            <span class="product-name">
                                {{ product_list.product_name }}            
                            </span>
                        </h6>
                        <div class="price-container clearfix">
                            <span class="price-box" style="margin-bottom:0px;white-space:normal;">
                                <span class="price">
                                    <span>R</span>
                                    <span>{{ product_list.product_price }}</span>
                                </span>
                                
                            </span>
                        </div>
				</div>
			</div>
		</div>
	</a>
        {% endfor %}
</div>
{% for page_num in product.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
    {% if product.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('home.shop_by_category', category_name = for_pagi.category_name , page = page_num)}}">{{page_num}}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4" href="{{ url_for('home.shop_by_category', category_name = for_pagi.category_name , page = page_num)}}">{{page_num}}</a>
    {%endif%}
{%else%}
...
{%endif%}
{% endfor %}

{% else %}
<div class="container-fluid">
    <h2 class="center">
        <p>
            No products have been added for this category please come back later
        </p>
    </h2>
</div>
{% endif %}

    {% endif %}
    

{% endblock %}