Clivia Backend😪😪😯/app/admin/routes.py
import os
from flask import ( flash, render_template, Blueprint, url_for, abort, redirect,
request
)
from flask_login import current_user, login_required
from app.admin.forms import CategoriesForm, ProductsForm
from app.models import Categories, Products,Order
from app import photos
from config import Config
import gc
from app import db

admin = Blueprint('admin', __name__)



def check_admin():
	if not current_user.is_admin:
		abort(403)


@admin.route('/categories', methods = ['GET','POST'])
@login_required
def list_categories():
	'''
	Get all product categories
	first check if user is an admin
	'''


	check_admin()

	categories = Categories.query.all()

	return render_template('admin/categories/categories.html', title = "Product Categories",
		categories = categories)


@admin.route('/categories/add/', methods = ['GET','POST'])	
def add_category():
	"""
	add a category to the
	database
	"""
	check_admin()

	add_category = True

	form = CategoriesForm()
	
	if form.validate_on_submit():
		filename = request.files['image']
		_, f_ext = os.path.splitext(filename.filename)
		name = form.name.data
		picture_fn = name + f_ext
		photos.save(filename, name = picture_fn)
		url = photos.url(picture_fn)
		category = Categories(category_name=form.name.data, category_image = url)
		try:
			db.session.add(category)
			db.session.commit()
			flash("You have successfully added a new category")
			gc.collect()
		except Exception as e:
			flash('Error: category name already exits. ')
			
		return redirect(url_for('admin.list_categories'))
	return render_template('admin/categories/category.html', action = "Add", form = form,
		add_category = add_category, title = "Add Categories")



@admin.route('/categories/edit/<int:id>', methods = ["GET","POST"])
def edit_category(id):
	'''
		Edit a category name
	'''

	check_admin()

	add_category = False

	category = Categories.query.get_or_404(id)

	form =CategoriesForm(obj=category)
	if form.validate_on_submit():
		filename = request.files['image']
		_, f_ext = os.path.splitext(filename.filename)
		name = form.name.data
		picture_fn = name + f_ext
		#get the name of the previous image
		previous_img_name = picture_fn
		photos.save(filename, name = picture_fn)
		url = photos.url(picture_fn)

		category.category_name = form.name.data
		category.category_image = url
		db.session.commit()
		gc.collect()
		flash("You have successfully edited the category")

		#remove the changed picture from the folder
		img_dir = Config.UPLOADED_PHOTOS_DEST+'/'
		os.remove(img_dir+previous_img_name)

		#redirect to the categories page
		return redirect(url_for('admin.list_categories'))
	#form.description.data = category.description
	form.name.data = category.category_name

	return render_template('admin/categories/category.html', action="Edit",
                           add_category=add_category, form=form,
                           category=category, title="Edit Category")




@admin.route('/categories/delete/<int:id>', methods = ["GET","POST"])
def delete_category(id):
	category = Categories.query.get_or_404(id)
	
	#get image extension
	_, f_ext = os.path.splitext(category.category_image)
	
	previous_img_name = category.category_name + f_ext
	img_dir = Config.UPLOADED_PHOTOS_DEST+'/'
	os.remove(img_dir+previous_img_name)
	db.session.delete(category)
	db.session.commit()
	gc.collect()
	flash("You have successfully deleted a Category")

	return redirect(url_for('admin.list_categories'))
'''
	return render_template('admin/categories/category.html',
	title = "Delete Category")
'''
@admin.route('/products/')
@login_required
def list_products():
	check_admin()
	'''
	list all products
	'''
	products = Products.query.all()

	return render_template('admin/products/products.html', title = 'Products', products = products)



@admin.route('/products/add/', methods = ["GET","POST"])
@login_required
def add_product():
	'''
	add a product to the database
	'''

	add_product = True

	form = ProductsForm()
	if form.validate_on_submit():
		filename = request.files['image']
		_, f_ext = os.path.splitext(filename.filename)
		name = form.name.data
		picture_fn = name + f_ext
		photos.save(filename, name = picture_fn)
		url = photos.url(picture_fn)
		product = Products(product_name = form.name.data,
		product_price = form.price.data,product_image = url,
		product_description = form.description.data, product_stock = form.stock.data )
		product.products_categories = form.categories.data
		try:
			#add a product to the database
			db.session.add(product)
			db.session.commit()
			gc.collect()
			flash("You have successfully added a product")
		except:
			# in case product name already exists
			flash("Error: product name already exits")
		
		# redirect to the roles page
		return redirect(url_for('admin.list_products'))
	#load product template
	return render_template('admin/products/product.html', add_product = add_product,
	form = form, title = "Add Product")



@admin.route('/products/edit/<int:id>',  methods = ["GET","POST"])
@login_required
def edit_product(id):
	'''
	edit product
	'''
	check_admin()


	add_product = False

	product = Products.query.get_or_404(id)
	form = ProductsForm(obj=product)
	if form.validate_on_submit():
		filename = request.files['image']
		_, f_ext = os.path.splitext(filename.filename)
		
		name = form.name.data
		picture_fn = name + f_ext
		
		#get the name of the previous image
		previous_img_name = picture_fn

		photos.save(filename, name = picture_fn)
		url = photos.url(picture_fn)

		product.product_name = form.name.data
		product.product_price = form.price.data
		product.product_image = url 
		product.product_description = form.description.data
		product.product_stock = form.stock.data
		db.session.commit()
		gc.collect()

		#remove the changed picture from the folder
		img_dir = Config.UPLOADED_PHOTOS_DEST+'/'
		os.remove(img_dir+previous_img_name)
		
		flash('You have successfully edited a product')
		#redirect to the products page
		redirect(url_for('admin.list_products'))

		form.name.data = product.product_name
		form.price.data = product.product_price
		form.image.data = product.product_image  
		form.description.data = product.product_description
		form.stock.data = product.product_stock 

	return render_template('admin/products/product.html', add_product = add_product,
		form = form, title = "Edit Product")


@admin.route('/products/delete/<int:id>', methods = ["GET","POST"])
@login_required
def delete_product(id):
	'''
	Delete a product from the database
	'''
	check_admin()
	
	product = Products.query.get_or_404(id)
	
	#get image extension
	_, f_ext = os.path.splitext(product.product_image)
	
	previous_img_name = product.product_name+f_ext
	img_dir = Config.UPLOADED_PHOTOS_DEST+'/'
	#remove the changed picture from the folder
	os.remove(img_dir+previous_img_name)		
	
	db.session.delete(product)
	db.session.commit()
	gc.collect()
	flash("You have successfully deleted a product")
	
	return redirect(url_for('admin.list_products'))
	

	
@admin.route('/orders/')
@login_required
def list_orders():
	check_admin()
	'''
	list all orders
	'''
	orders = Order.query.all()

	return render_template('admin/orders.html', title = 'Orders', orders = orders)
	

Clivia Backend😪😪😯/app/home/routes.py
from app import app, db
from flask import ( render_template, request, redirect, url_for, session,
	flash,Blueprint, abort
	)

from flask_login import current_user, login_required

from app.models import User, Categories, Products,Kart
from app.admin.forms import Variations
import random
home = Blueprint('home', __name__)


@home.route('/admin/dashboard/')
@login_required
def admin_dashboard():
	#preventing non admins from accessing the page
	if not current_user.is_admin:
		abort(403)
	return render_template('admin/admin_dashboard.html' , title = "Dashboard")

@home.route('/')
def landing():
	ids = []
	c = Products.query.all()
	for s in c:
		ids.append(s.id)
	sorter = []
	for i in range(3):
		random.randint(1,1000)
		if i in ids:
			sorter.append(i)
	products = Products.query.all()
	return render_template('head.html', products = products, sorter = sorter)

@home.route('/home/')
def homepage():		
	categories = Categories.query.all()
	products = Products.query.all()

	if current_user.is_anonymous:
		count = 0
	else:
		count = Kart.query.filter_by(user_id =current_user.id).count()
	return render_template("home/index.html", title = 'Website name',
	categories = categories, products = products, count=count)

@home.route('/<string:category_name>/')
def shop_by_category(category_name):
	if current_user.is_anonymous:

		count = 0
	else:
		count = Kart.query.filter_by(user_id =current_user.id).count()

	page = request.args.get('page',1, type=int)

	category = Categories.query.filter_by(category_name=category_name).first_or_404()

	product = Products.query.filter_by(categories_id=category.id)\
		.order_by(Products.product_name).paginate(page=page, per_page=6)
	
	for_pagi = Categories.query.filter_by(category_name = Categories.category_name).first_or_404()
	return render_template("home/shop_by_category.html", category = category,\
		product = product, title = "Category: "+ category.category_name,count=count,\
		for_pagi = for_pagi)


@home.route('/productdetails/<string:product_name>/', methods = ["GET","POST"])
def product_details(product_name):
	if current_user.is_anonymous:
		count = 0
	else:
		count = Kart.query.filter_by(user_id =current_user.id).count()
		user =current_user.id
	form = Variations()

	product_detail = Products.query.filter_by(product_name=product_name).first_or_404()
		
	# add to cart
	if form.validate_on_submit():
		# annonymous users
		if current_user.is_anonymous:
			flash('please login before you can add items to your shopping cart','warning')
			return redirect(url_for("home.product_details",\
				product_name = product_detail.product_name))
		# authenticated users
		product_detail.product_size = form.sizes.data
		cart = Kart(user_id=user, product_id=product_detail.id, quantity=1,
		subtotal = product_detail.product_price)
		db.session.add(cart)
		db.session.commit()

		flash("{} has been added to cart".format(product_detail.product_name))	
		return redirect(url_for('home.product_details',\
			product_name = product_detail.product_name ))
	return render_template("home/productdetails.html",
		product_detail = product_detail,title = product_detail.product_name,
		form =form,count=count)

Clivia Backend😪😪😯/app/users/routes.py
from app import app
from flask import (render_template, request, redirect, url_for, session,
	flash, Blueprint, jsonify
	)

from app.models import User, ShippingInfo, Kart,Products,Order,association_table

import gc

from flask_login import (current_user, login_user, logout_user, login_required
	)
from app.users.forms import (ShippingForm,RequestResetForm,ResetPasswordForm,
	CartForm)
from app import db, mail
from flask_mail import Message
from random import randint
users = Blueprint('users', __name__)



def ShippingPrice():
	'''
	calculate the price of shipping if items is greater than 5 shipping is 2500
	else 1200
	'''
	if current_user.is_authenticated:
		#check this otherwise revert to 
		#item_num = Kart.query.filter_by(user_id = Kart.user_id).count()
		item_num = Kart.query.filter_by(user_id = current_user.id).count()
	else:
		item_num = Kart.query.filter_by(user_id = 0).count()
	
	shipping_price = 0
	if item_num >= 1:
		shipping_price = 10
	elif item_num >= 5:
		shipping_price = 100
	else:
		pass
	return shipping_price

def subtotals():
	if current_user.is_authenticated:
		#check this otherwise revert to 
		#item_num = Kart.query.filter_by(user_id = Kart.user_id).count()
		get_products = Kart.query.filter_by(user_id = current_user.id).all()
	else:
		get_products = Kart.query.filter_by(user_id = 0).all()
	
	items_subtotal = 0
	#get_products = Kart.query.filter_by(user_id = Kart.user_id).all() 
	
	for price in get_products:
		items_subtotal+=int(price.subtotal)
	return items_subtotal
@users.route('/test')
def testcart():
	return render_template('testcart.html')
	
@users.route('/cart/',methods = ["GET","POST"])
def cart():	
	if current_user.is_anonymous:
		count = 0
		user = 0 
		cartlist = []
	else:
		user = current_user.id
		count = Kart.query.filter_by(user_id =user).count() 
		cartlist = Kart.query.filter_by(user_id=user).all()
	
	form = CartForm()
	# fetch cart data 
	
	#shipping = ShippingInfo.query.all()
	price = ShippingPrice()
	items_subtotals = subtotals() 
	#for annoymous users
	if current_user.is_anonymous:
		flash('please login or register to your Clivia account to be able to add a shipping address')			
		return render_template('users/cart.html', count= count, cartlist= cartlist,
	title = "Cart", form = form, price=price, items_subtotals=items_subtotals)
	
	return render_template('users/cart.html', count= count, cartlist= cartlist,
	title = "Cart", form = form, price=price,items_subtotals=items_subtotals)



@users.route('/cart/update/<int:id>',methods = ["POST"])
def quantity_update(id):
	cart_item = Kart.query.get_or_404(id)
	quantity = request.form["quantity"]
	cart_item.quantity = quantity
	item_total = cart_item.product.product_price * int(quantity)
	cart_item.subtotal = item_total
	items_subtotal = subtotals()
	db.session.commit()
	gc.collect()		
	return jsonify({"result":"success", "item_total":item_total, "subtotal":items_subtotal})



@users.route('/cart/remove/<int:id>',methods = ["GET","POST"])
def remove_item(id):
	cart_item = Kart.query.get_or_404(id)
	db.session.delete(cart_item)
	db.session.commit()
	gc.collect()
	return redirect(url_for('users.cart'))

def send_success_mail(user):
	msg = Message('Item(s) Purchased', sender='noreply@demo.com',
	recipients=[user.email])
	msg.body = f'''You have successfully purchased items from our store.
These items will be shipped withing 48hours, Thank you.
If you did not make this request simply ignore this request and no changes will be made.
'''
	mail.send(msg)

@login_required
@users.route('/success',methods = ["GET"])
def success():
	u = current_user.id
	flash('Transaction successful', 'success')
	if request.method == "GET":
		user = current_user.email
		send_success_mail(user)
		ref = randint(1,10000)
		order = Order(user_id=u,order_ref = ref)
		db.session.add(order)
		db.session.commit()
		items = Kart.query.filter_by(user_id=u).all()
		for i in items:
			ids = i.product
			order.my_orders.append(ids)
			db.session.delete(i)
		db.session.commit()
		gc.collect()
	return render_template('users/charge.html')
@login_required
@users.route('/failure')
def failed():
	flash('transaction Failed', 'danger')
	return render_template('users/failed.html')

@users.route('/profile/', methods = ["GET", "POST"])
def profile():
	if current_user.is_anonymous:
		count = 0
		user = 0 
		
	else:
		user = current_user.id
		count = Kart.query.filter_by(user_id =user).count()
		order = Order.query.filter_by(user_id = user)
		items = Kart.query.filter_by(user_id=user).all()

	form = ShippingForm()
	shipping = ShippingInfo.query.all()
	if form.validate_on_submit():
		info = ShippingInfo(address1=form.address1.data,address2=form.address2.data,
		postcode=form.postcode.data,city=form.city.data,
		state=form.state.data,country=request.form['country'])
		db.session.add(info)
		db.session.commit()
		gc.collect()
		flash('shipping information was submitted successfully','success')
		return redirect(url_for('users.profile'))
	return render_template('users/profile.html', title = "Account page",form=form,
	shipping = shipping, count=count, order = order,items=items)


def send_reset_email(user):
	token = user.get_reset_token()
	msg = Message('Password Reset Request', sender='noreply@demo.com',
	recipients=[user.email])
	msg.body = f'''To reset your password, visit the following link:
{ url_for('users.reset_token', token = token, _external =True) }
If you did not make this request simply ignore this request and no changes will be made.
'''
	mail.send(msg)


@users.route('/profile/reset_password/',methods = ["GET","POST"])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('home.homepage'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset you password','info')
		return redirect(url_for('auth.login'))
	return render_template('users/reset_request.html',title = 'Reset password',
	form = form)




@users.route('/profile/reset_password/<token>/',methods = ["GET","POST"])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('home.homepage'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		user.password_hash = user.set_password(form.password.data)
		db.session.commit()
		gc.collect()
		flash('Your password has been successfully updated', 'success')
		return redirect(url_for('auth.login'))
	return render_template('users/change-password.html',title = 'Reset password',
	form = form)

Clivia Backend😪😪😯/app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
    <div class="content-section">
      
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control") }}
                        <small id="passwordHelpInline" class="text-muted">
                                Must be 8-25 characters long.
                        </small>
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
                <small class="text-muted ml-5">
                    Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
                </small>
            </div>
        </form>
      </div>

{% endblock%}

Clivia Backend😪😪😯/app/templates/prevcart.html
{% extends "base.html" %}
<head>
	{%block head%}
	<link href="{{ url_for('static', filename='css/cart.css')}}" rel="stylesheet">
	{%endblock%}

</head>
{% block body %}
<body>
		
<div class="wrapper">
	<header class="heading cf">
		<h5>My Cart</h5>
	</header>
	{% if current_user.is_authenticated %}
	<div class="outerbox">
		<div class="innerbox">
			<div class="cart-content">
				<ul class="item-wrapper">
						{% for items in cartlist %}
					<li id="cart_items" class="cart-items">
						<div class="infoWrap">
							<div class="item-description">
								<img src="{{ items.product.product_image }}" class="item-img">
								<h6 class="item-name">
									{{ items.product.product_name }}	
									
										<br>
									<div class="small">
										<span>Size:</span> 
										<span>{{ items.product.product_size }}</span>
									</div>
										
								</h6>
								<br>
								<div class="xtra">
									<form action="{{url_for('users.quantity_update', id=items.id)}}" class="form-inline"
									style="padding:0;margin:0;">
										<p>
											<input id="minus-btn" type="button" class="minus-btn{{items.id}}" value="-">
												<input type="text" name="quantity" class="qty form-control-sm"
												id="qty{{items.id}}" value="{{items.quantity}}" readonly>
											<input id="plus-btn" type="button" class="plus-btn{{items.id}} 	" value="+">	
											  x <span class="iso">R</span> <span class="item-price{{items.id}}"> {{ items.product.product_price }}</span>
											  <p> <span id="loading{{items.id}}" class="loading_bkg"></span> </p>
										</p>
										
									</form>
									<p class="stockStatus">
										In Stock
									</p>
									
								</div>

							</div>
							<div class="prod-total item-description">
								<p> <span class="iso">R</span> <span class="item-total{{items.id}} item-total">{{items.subtotal}}</span></p>
							</div>


							<div class="remove-item item-description">
								<a href="{{ url_for('users.remove_item', id=items.id) }}" class="remove">x</a>	
							</div>
						</div>
					</li>
					
                    {% endfor %}
				</ul>

			</div>
		
				
		</div>
	</div>
<footer class="cart-footer">
	<div class="subtotal cf">
		
    <ul>
	  <li class="totalRow"><span class="label">Subtotal</span>
		<span class="iso">R</span>
		<span id="subtotal_value" class="value">{{items_subtotals}}</span>
	</li>
	<li class="totalRow"><span class="label">Shipping</span>
		<span class="iso">R</span>
		<span id="shipping_price" class="value">{{ price }}</span>
	</li>

	<li class="totalRow final"><span class="label">Total</span>
		<span class="iso">R</span>
		<span id="total-final" class="value">{{items_subtotals + price}}</span>
	</li>
    </ul>
  </div>

  
		<div class="checkoutcontainer">
			<a href="#" id="checkout" data-toggle="modal" data-target="#exampleModalCenter">
				<span class="checkout-text">Checkout</span>
			</a>
		</div>
			<!-- Modal -->
			<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalCenterTitle">Select Payment Method</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
						<div class="row">
								<div class="col-md-4">
										<script type="text/javascript" src="https://ravesandboxapi.flutterwave.com/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
										<form method="POST">
											<script src="https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js"></script>
											<button type="button" onClick="payWithRave()" class="btn btn-outline-success">Ravepay</button>
										</form>
								</div>
								<div class="col-md-4">other payment method</div>
							  </div>
						
				</div>
				
				</div>
			</div>
			</div>
	
	<span class="cart-copyright">
		powered by <a href="#" class="authored">SphaBSB</a>
	</span>
</footer>
</div>
{% for items in cartlist %}
<script>
	$(document).ready(function(){

		$('.minus-btn{{items.id}}').on('click', function(e) {
    		e.preventDefault();
    		var quantity =parseInt($("#qty{{items.id}}").val());
    		if (quantity > 1) {
    			quantity = quantity - 1;
    		} else {
    			quantity = 1;
			}
			$("#qty{{items.id }}").attr("disabled");
			$("#loading{{items.id}}").addClass("loading");
			req = $.ajax({
			url:"{{url_for('users.quantity_update',id = items.id)}}",
			type:"POST",
			data: {quantity:quantity}
			});
			req.done(function(data){
			$("#loading{{items.id}}").removeClass("loading");
			$("#qty{{items.id }}").removeClass("disabled");
			//$("#qty{{items.id}}").fadeOut(1000).fadeIn(1000);
			new_price = $(".item-total{{items.id}}").text(data.item_total).fadeOut(100).fadeIn(1000);
			$("#subtotal_value").text(data.subtotal);
			$("#total-final").text(parseFloat($("#subtotal_value").text()) + parseFloat({{price}}));
		});

		$("#qty{{items.id}}").val(quantity)

		});

		$('.plus-btn{{items.id}}').on('click', function(e){
			e.preventDefault();
			var quantity = parseInt($('#qty{{items.id}}').val())
			if (quantity<20){
				quantity = quantity +1;
			}else{
				quantity = 20;

			}
			$('#qty{{items.id}}').attr("disabled");
			$("#loading{{items.id}}").addClass("loading");
			req = $.ajax({
			url:"{{url_for('users.quantity_update',id = items.id)}}",
			type:"POST",
			data: {quantity:quantity}
			});
			req.done(function(data){
				$("#loading{{items.id}}").removeClass("loading");
				$("#qty{{items.id }}").removeClass("disabled");
				//$("#qty{{items.id}}").fadeOut(1000).fadeIn(1000);
				new_price = $(".item-total{{items.id}}").text(data.item_total).fadeOut(100).fadeIn(1000);
				$("#subtotal_value").text(data.subtotal);
				$("#total-final").text(parseFloat($("#subtotal_value").text()) + parseFloat({{price}}));
			});

			$("#qty{{items.id}}").val(quantity)


			});




		$(document).on('blur','#qty{{items.id }}', function(){
		var quantity =parseInt($("#qty{{items.id}}").val());
		//$("#subtotal_value").text(subtotal);
		$("#qty{{items.id }}").addClass("disabled");
		
		req = $.ajax({
			url:"{{url_for('users.quantity_update',id = items.id)}}",
			type:"POST",
			data: {quantity:quantity},

			beforeSend: function(){
				$("#loading{{items.id}}").addClass("loading");
			},
			complete: function(){
				$("#loading{{items.id}}").removeClass("loading");
			},
			
		});
		
		//remove loading class here
		req.done(function(data){
			//$("#qty{{items.id}}").fadeOut(1000).fadeIn(1000);
			new_price = $(".item-total{{items.id}}").text(data.item_total).fadeOut(100).fadeIn(1000);
			$("#subtotal_value").text(data.subtotal);
			$("#total-final").text(parseFloat($("#subtotal_value").text()) + parseFloat({{price}}));
		});

		});
});

</script>

<script>
    const API_publicKey = "FLWPUBK_TEST-fe0814ab10b8b42b0499ae3ad269ddeb-X";

    function payWithRave() {
        var x = getpaidSetup({
            PBFPubKey: API_publicKey,
            customer_email: "{{current_user.email }}",
            amount: {{items_subtotals + price}},
            customer_phone: "{{current_user.phonenumber }}",
            currency: "R",
            txref: "rave-123456",
            onclose: function() {},
            callback: function(response) {
                var txref = response.tx.txRef; // collect txRef returned and pass to a 					server page to complete status check.
                console.log("This is the response returned after a charge", response);
				
                if (
                    response.tx.chargeResponseCode == "00" ||
                    response.tx.chargeResponseCode == "0"
                ) {
					
                    // redirect to a success page
					window.location = "{{url_for('users.success')}}"; //Add your success page here
                } else {
                    // redirect to a failure page.
					window.location = "{{url_for('users.failed')}}";
                }

                x.close(); // use this to close the modal immediately after payment.
            }
        });
    }
</script>

{% endfor %}


{% else %}
<div class="outerbox">
	<div class="innerbox">
		<div class="cart-content">
			<ul class="item-wrapper">
				<li id="cart_items" class="cart-items">
					<div class="infoWrap">
						<div class="item-description">
							

						</div>
						<div class="prod-total item-description">
						</div>


						<div class="remove-item item-description">	
						</div>
					</div>
				</li>
				
			</ul>

		</div>
	
			
	</div>

	

</div>
<footer class="cart-footer">
<div class="subtotal cf">
<ul>
  <li class="totalRow"><span class="label">Subtotal</span>
	<span class="iso">R</span>
	<span id="subtotal_value" class="value">0</span>
</li>
<li class="totalRow"><span class="label">Shipping</span>
	<span class="iso">R</span>
	<span id="shipping_price" class="value">0</span>
</li>

<li class="totalRow final"><span class="label">Total</span>
	<span class="iso">R</span>
	<span id="total-final" class="value">0</span>
</li>
</ul>
</div>
	<div class="checkoutcontainer">
		<a href="#" id="checkout">
			<span class="checkout-text">Checkout</span>
		</a>
	</div>

<span class="cart-copyright">
	powered by <a href="#" class="authored">SphaBSB</a>
</span>
</footer>
</div>

{% endif %}

</body>



{% endblock %}